### ISSUE TITLE
Snapping is broken in horizontal RecyclerViews when in RTL

### ISSUE THREAD

**Issue by osama** [rubensousa/RecyclerViewSnap#1]
Hey,  
Thanks for sharing this example! I was playing around with the `GravitySnapHelper` and noticed an issue in RTL, which would cause the carousel to scroll back to the first item, regardless of how far along it was in the list of items.
<img src="https://cloud.githubusercontent.com/assets/1403575/18137475/6fffc3ae-6f76-11e6-89cf-00153a6ce108.gif" width="250px"/>

After investigating a bit, I realized that this is because the support library's `OrientationHelper` always assumes that start is left and end is right (which doesn't hold true when in RTL). Ideally, this would be fixed in a support library update, but [I've created a gist of my modifications to `GravitySnapHelper` if anyone else runs across this issue and would like to fix it temporarily](https://gist.github.com/osama/952341eb1e158ba6150b94dcdc69043f). I haven't tested it too much with `Gravity.END` so please let me know if you notice any issues in my calculation there.

EDIT: [Submitted to the AOSP bug tracker.](https://code.google.com/p/android/issues/detail?id=221408)

**Comment by rubensousa** [comment]
Thanks for your work! Do you mind if I integrate these changes in the repo?

**Comment by osama** [comment]
No, go for it! I made another slight modification to the script since it wasn't showing the last item in certain cases. However, I've noticed that the RTL stuff is still broken, particularly on larger screens and I haven't yet been able to determine why.

**Comment by rubensousa** [comment]
If there's still issues, I think we should just use a custom "OrientationHelper".

**Comment by osama** [comment]
Yeah, [see Google's response here](https://code.google.com/p/android/issues/detail?id=221408) 😐

> OrientationHelper does not account for RTL, this is by design. LayoutManagers, if they support RTL, handle this.
> OrientationHelper works on absolute screen coordinates.

**Comment by rubensousa** [comment]
Will be out in 0.2.
