### ISSUE TITLE
padding / clipToPadding="false" does not work

### ISSUE THREAD

**Issue by jeffbordon** [rubensousa/RecyclerViewSnap#10]
When I apply
> android:padding="8dp"
> android:clipToPadding="false"

to my RecyclerView, the list element does not "snap" but jumps between position with padding and without padding. Any ideas how to fix that? Thanks!

**Comment by rubensousa** [comment]
Every element or just a particular one?

**Comment by jeffbordon** [comment]
Happens to me with every element...

**Comment by rubensousa** [comment]
Which gravity are you using? Are you saying it works without padding?

**Comment by jeffbordon** [comment]
Without padding and clipToPadding=false it works, however I would like the padding... Here is my full layout (the overscroll-param does not change the behavior):
```
<LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="vertical"
 >

<RecyclerView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never"
            android:padding="8dp"
            android:clipToPadding="false"
            android:orientation="horizontal" />
</LinearLayout>
```

**Comment by rubensousa** [comment]
The outer LinearLayout isn't necessary in that case. Try removing it or applying clipToPadding to it as well.
Also, recyclerview doesn't handle "android:orientation"

**Comment by jeffbordon** [comment]
Thanks for the response. I finally found that `clipToPadding="false"` was not the problem.

The root cause for my problem seems to be that I have my snapping RecyclerView inside a vertically scrolling RecyclerView on which I apply 
`((SimpleItemAnimator) mRecyclerView.getItemAnimator()).setSupportsChangeAnimations(false);`
to disable layout transitions (to avoid the flickering effect on click).

Then I re-enable the layout transitions only for the LinearLayout (the one above you recommended to remove) holding my snapping RecyclerView by calling 
`mLinearLayout.setLayoutTransition(new LayoutTransition());`

Still investigation this issue...

**Comment by rubensousa** [comment]
Can you provide sample, through a github repository or just a zip file?

What changes are you introducing on click that add a flickering effect? I think you're disabling layout transitions the wrong way though. If you want to disable them in that LinearLayout, you should pass null in setLayoutTransition instead of changing RecyclerView's ItemAnimator.

**Comment by rubensousa** [comment]
Any updates?

**Comment by rubensousa** [comment]
Closing due to no response.
