### ISSUE TITLE
Auto left scrolling

### ISSUE THREAD

**Issue by leonardo2204** [rubensousa/RecyclerViewSnap#11]
I'm using the SnapHelper inside a recyclerView, but I found out that after scrolling the list for a bit (thus recycling its views) the RecyclerView automatically scrolls to the start of the list after any scroll motion, I mean, I scroll for instance, to the middle of the list. it suddenly goes to the first item, without any user interaction.

My code:
```Java
@Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
SnapHelper snapHelper = new GravitySnapHelper(Gravity.BOTTOM);
            productsRecyclerView.setOnFlingListener(null);
            snapHelper.attachToRecyclerView(productsRecyclerView);
}
```

An image demonstrating the issue: (sorry for the hogging, my mac sucks)
[Imgur](http://i.imgur.com/PfyRJB6.gifv)

Any thoughts on that ?

**Comment by rubensousa** [comment]
Why are you using Gravity.BOTTOM instead of Gravity.START? In that demo, you're displaying an horizontal RecyclerView

**Comment by leonardo2204** [comment]
That was dumb haha, sorry about that, changing to START solved it.
Anyway, using END still gives me the same weird behaviour, any ideas ?

Thanks

**Comment by rubensousa** [comment]
Can you record it again for the Gravity.END case?

**Comment by leonardo2204** [comment]
It's the very same behaviour.

**Comment by rubensousa** [comment]
But it helps anyway :)

Are you using the same code as the above?

**Comment by leonardo2204** [comment]
Exactly, but instead of using BOTTOM I'm using END.
[A new record :)](http://imgur.com/a/Nuwnr)

Thanks for the quick reply !

**Comment by rubensousa** [comment]
Weird, in that recording it seems like Gravity.START is applied. Where are you setting the LayoutManager to the RecyclerView?

**Comment by leonardo2204** [comment]
Yeah, that's the same impression I have.
The entire snippet:

```Java
 LinearLayoutManager layoutManager = new LinearLayoutManager(mContext);
            layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);
            productsRecyclerView.setLayoutManager(layoutManager);
            CampaignCarouselAdapter adapter = new CampaignCarouselAdapter(mCampaign.getProducts(), mContext, mCampaign.showMoreButtonCarousel());
            productsRecyclerView.setAdapter(adapter);

            SnapHelper snapHelper = new GravitySnapHelper(Gravity.END, false);
            productsRecyclerView.setOnFlingListener(null);
            snapHelper.attachToRecyclerView(productsRecyclerView);
```

**Comment by rubensousa** [comment]
I can't find anything wrong. I would suggest you to try and isolate the cause by creating a simple layout based on the sample in this repository.

Check if you're sharing the instance of productsRecyclerView anywhere and setting another snaphelper.

**Comment by leonardo2204** [comment]
Sure, I'll give it a try and share the feedback in a while !

Thanks again for the help !

**Comment by rubensousa** [comment]
Any updates on this?

**Comment by leonardo2204** [comment]
I have no time to check this out, gonna close the issue. If it happens occuring, I'll reopen it !
Thanks

**Comment by c0d3sling3r** [comment]
I have same issue. On a horizontal RTL recyclerview which has `GravitySnapHelper(Gravity.END)` property.

**Comment by SetareMaghari** [comment]
@mojsho could you solve it?
