### ISSUE TITLE
Reduce minSdkVersion?

### ISSUE THREAD

**Issue by simonrob** [rubensousa/RecyclerViewSnap#17]
Thanks for the great library - it works perfectly!

Just one issue - at the moment I'm having to override its minSdkVersion (by using `<uses-sdk tools:overrideLibrary="com.github.rubensousa.gravitysnaphelper"/>` in a manifest file).

As the RecyclerViewSnap library is intended solely to augment the functionality of the RecyclerView v7 support library, could you reduce minSdkVersion to the same as the v7 libraries (e.g., 9), rather then the current version 15?

**Comment by rubensousa** [comment]
Yes, I can do this :)
