### ISSUE TITLE
Snap Center: How to set first item to center

### ISSUE THREAD

**Issue by HuuNguyen312** [rubensousa/RecyclerViewSnap#20]
![snap](https://cloud.githubusercontent.com/assets/9895294/24490046/f95a3254-154a-11e7-9ced-21296561c571.PNG)

Snap Center: How to set first item to center. Thanks

**Comment by rubensousa** [comment]
You could add an invisible viewholder with the same width as the first item.

**Comment by HuuNguyen312** [comment]
Thanks for your answer. I solved this problem in another way by using RecyclerView.ItemDecoration
