### ISSUE TITLE
SCROLL_STATE_IDLE is never called in case of scrolling up

### ISSUE THREAD

**Issue by dawidfiruzek** [rubensousa/RecyclerViewSnap#24]
In case of swiping up when we are focused on first element, SCROLL_STATE_IDLE is never called.
The same issue occurs when we are focused on second or third element and we swipe up really fast.
This problem does not occur in case of using LinearSnapHelper

**Comment by rubensousa** [comment]
This isn't part of the library. Those events are called by the RecyclerView itself.

Anyway, I've updated the sample with a vertical list of items that fills the whole screen. The onSnap method seems to be called properly. Can you check the sample again?

**Comment by rubensousa** [comment]
Closing due to no response.
