### ISSUE TITLE
Snap to a custom position 

### ISSUE THREAD

**Issue by mspmax** [rubensousa/RecyclerViewSnap#25]
Hi,

First of all, thank you for your work and appreciate it. This is more like a requirement than an issue.
![screenshot_20170804-135308](https://user-images.githubusercontent.com/4340194/28955205-1fd7059c-7928-11e7-985c-cb8aa102bd1d.png)

So I have this requirement to snap the horizontal recyclerView to the left edge of the screen (exactly like latest play store update for movies) during the first scroll event. Does the library support this kind of requirement ? or do you have any bright work around's?

**Comment by rubensousa** [comment]
I can think of a possible way: add an invisible placeholder item with X width (in this case, it seems around 4x the usual item's width) and then use GravityPagerSnapHelper.

Let me know if this works :)

**Comment by rubensousa** [comment]
Closing due to no response
