### ISSUE TITLE
Snap center can't see the last item completely

### ISSUE THREAD

**Issue by dingbuoyi** [rubensousa/RecyclerViewSnap#26]
If you change the CardView's "layout_width" to 152dp which is in the adapter.xml,
then for the type which is "Snap center" in the demo app can't see the first and last item completely.

```xml
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="152dp"
    android:layout_height="wrap_content"
    android:layout_margin="4dp"
    android:clickable="true"
    android:foreground="?attr/selectableItemBackground"
    android:orientation="vertical">
```
![image](https://user-images.githubusercontent.com/476649/29554829-34484d5e-8753-11e7-918b-7c977ed9468d.png)

**Comment by rubensousa** [comment]
Snap center means: center the closest item near the center. In this case it's the Slides card. The other views don't matter.

**Comment by dingbuoyi** [comment]
@rubensousa 

Thank you for reply, the problem is that you can't see the last item completely.
Every time you slide from right to left when the recycle view has reached the end, it will rebound and make the last but one item in the center of the  recycle view.

**Comment by rubensousa** [comment]
I know, but this isn't a library issue. If you need to show the last item, you need to pick another SnapHelper or adjust the card size so that it can fit at least 3 visible items at the same time :)

**Comment by rubensousa** [comment]
Unless you mean extending LinearSnapHelper to something that overcomes this? As in a feature request.

**Comment by dingbuoyi** [comment]
@rubensousa 

Thank you for reply, you are right . I am trying to implement a custom SnapHelper which can overcomes this.

**Comment by rubensousa** [comment]
@dingbuoyi I'll add this in 2.2.0.

**Comment by rubensousa** [comment]
Let's follow this in #21
