### ISSUE TITLE
How to scroll to postion with Snap?

### ISSUE THREAD

**Issue by LoveqLRC** [rubensousa/RecyclerViewSnap#27]
I use the `mLayoutManager.scrollToPositionWithOffset(1, 0);`  method，but the snap effect not work well.

**Comment by rubensousa** [comment]
Seems like these work fine with snap:
```java
recyclerView.smoothScrollBy(400,0)
recyclerView.smoothScrollToPosition(6);
```

**Comment by LoveqLRC** [comment]
Thanks for your answer. I solved this problem in another way.
