### ISSUE TITLE
Sap can't reach the first and the last element after the first scroll

### ISSUE THREAD

**Issue by vascoV** [rubensousa/RecyclerViewSnap#38]
Hello,

Thi is my init screen
![24957009_10215315313984676_1139774752_o](https://user-images.githubusercontent.com/15817701/33720665-53d8d292-db6d-11e7-9b42-557acf3d4abc.jpg)
As soon as i scrol I am getting this:
![24957106_10215315313744670_1893402547_o](https://user-images.githubusercontent.com/15817701/33720675-608bb0cc-db6d-11e7-81a7-44593c4606f7.jpg)

I wanna be able to see one element in the middle and left and right the half of the other elements,
as soon as I reach the last element to be able to reach the whole rectangle not only the half

**Comment by rubensousa** [comment]
Which SnapHelper are you using?

**Comment by vascoV** [comment]
Hey @rubensousa I found this one implementation 'com.github.rubensousa:gravitysnaphelper:1.4'
and used it!

**Comment by vascoV** [comment]
fixed
