### ISSUE TITLE
Snap how to find the visiable item position?

### ISSUE THREAD

**Issue by WTMahone** [rubensousa/RecyclerViewSnap#39]
snapHelper.findTargetSnapPosition() can receive the visible item position?

**Comment by rubensousa** [comment]
I didn't understand the question, sorry. If you want to know which item is currently visible, you need to use the LinearLayoutManager's findFirstVisibleItemPosition().
Otherwise, if you want to know which item was snapped, you need to pass a SnapListener into GravitySnapHelper's constructor.

**Comment by WTMahone** [comment]
okey,thank you!
