### ISSUE TITLE
Create a library?

### ISSUE THREAD

**Issue by Piasy** [rubensousa/RecyclerViewSnap#4]
Thanks for your great work! Could you please create a library and host it on somewhere like bintray?

**Comment by rubensousa** [comment]
For GravitySnapHelper, right? I'll host it on jitpack since it's easier

**Comment by Piasy** [comment]
Great!

**Comment by rubensousa** [comment]
Done. It's on jcenter and mavencentral

``` groovy
compile 'com.github.rubensousa:gravitysnaphelper:0.1'
```
