### ISSUE TITLE
Dot Indicator using Snap Helper

### ISSUE THREAD

**Issue by kavidriod** [rubensousa/RecyclerViewSnap#41]
Hi,
 Can I create UI like this using Snap Helper?

![03_c_overview_list_accepted_by_me](https://user-images.githubusercontent.com/28779054/33863951-5102e3b8-df10-11e7-91d6-6b8e3fee36ef.png)

**Comment by rubensousa** [comment]
That should be a custom view instead.

**Comment by kavidriod** [comment]
Can I add Dot Page indicator custom view with RecyclerView Pager right?
