### ISSUE TITLE
Bad scrolling horizontally and vertically

### ISSUE THREAD

**Issue by sm-tester** [rubensousa/RecyclerViewSnap#43]
Hi @rubensousa, thank you for great library. I have scrolling problem when using this a library. I have a ViewPager and I have horizontal orientation RecyclerView inside secondary fragment page. All items of this RecyclerView is a vertical orientation RecyclerView. 
So, you can visualize structure like that:  vertical orientation RecyclerView is item of horizontal orientation RecyclerView is item of ViewPager. (RecyclerView->RecyclerView->ViewPager)

When you scrolling horizontally works not a stable and smoothly, works hardly and not works any time. 
When you scrolling vertically of vertical orientation RecyclerView not fully end, RecyclerView will be automatic scroll to head of the list. If you will scroll until end of list then stopped auto scrolling above.

For understanding my problem i created sample project, please look it:

[Sample project -> ProbaSnapRV.zip](https://github.com/rubensousa/RecyclerViewSnap/files/1590957/ProbaSnapRV.zip)

Video: 
![ScreenReq](https://user-images.githubusercontent.com/3168694/34407659-57fad8be-ebe1-11e7-952c-956ac1e1828c.gif)

 

Please, help me solve horizontally and vertically scrolling problems, i want they works smoothly

**Comment by rubensousa** [comment]
In HorizontalRVAdapter, you're using Gravity.START instead of Gravity.TOP:

```java
new GravitySnapHelper(Gravity.START).attachToRecyclerView(holder.verticalRV);
```

**Comment by sm-tester** [comment]
Thank you @rubensousa, but this solved just vertical scrolling problem, what do you thing about horizontal scrolling problem?

**Comment by sm-tester** [comment]
Do you have any suggestions to solving scrolling horizontally if vertical list view is empty or not empty situations. When you will scroll on the header("Horz item: *") works fine horizontally, but when scrolling with vertical list to horizontally not works is stable

**Comment by rubensousa** [comment]
Try removing this section inside HorizontalRVAdapter:

```java
verticalRV.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View view, MotionEvent motionEvent) {
                    view.getParent().requestDisallowInterceptTouchEvent(true);
                    return false;
                }
            });
```

**Comment by sm-tester** [comment]
I added this code because, i need vertical RecyclerView items will be clickable

**Comment by rubensousa** [comment]
Ok, then try adding an OnItemTouchListener to the verticalRV RecyclerView and handle the click on onInterceptTouchEvent. I'm going to close this since it's not related to SnapHelper anymore. StackOverflow is the best place for this kind of issues.

**Comment by sm-tester** [comment]
Thank you @rubensousa!!!
