### ISSUE TITLE
CoordinatorLayout does not scroll on list fling

### ISSUE THREAD

**Issue by jacekkrasowski** [rubensousa/RecyclerViewSnap#48]
I have a ViewPager having RecyclerView in each page.
ViewPager has layout behavior set to appbar_scrolling_view_behavior

when swiping list up, after finger is off the screen, fling starts, coordinator layout does not scroll, just the list moves up, appbar stays where the finger was left

**Comment by rubensousa** [comment]
Is this related to snapping or scrolling of AppBar? Seems like it's not related to this library.

**Comment by rubensousa** [comment]
Closing due to no response.
