### ISSUE TITLE
Scrolling issue with snap center

### ISSUE THREAD

**Issue by leicht-io** [rubensousa/RecyclerViewSnap#5]
This is only an issue with the snap-center functionality.
When i slide horizontally in the RecyclerView i cant slide vertically afterwards in the wrapping RecyclerView - it is like the horizontal RecyclerView steals the focus without clearing it afterwards. Please see this video:
http://i.imgur.com/5NwrR5s.gifv

**Comment by nikhilreprime** [comment]
this seems to be happening if you scroll to first or last element of list in recycler view
if you scroll back to one of the middle elements it can be vertically scrolled

do you have any solution for this

**Comment by rubensousa** [comment]
I still didn't have time to look at this. I've just added GravitySnapHelper as a library so you can easily update it when this and the other bugs get fixed.

**Comment by leicht-io** [comment]
@rubensousa thank you.

**Comment by leicht-io** [comment]
@rubensousa anything new regarding this bug?

**Comment by rubensousa** [comment]
I'll try to fix it this weekend, but can't promise anything.

**Comment by rubensousa** [comment]
I just updated the support library and I can't reproduce this again (24.2.1). Easiest solution ever :)

**Comment by leicht-io** [comment]
@rubensousa that did the trick! That's just perfect! Thank you for your time :)
