### ISSUE TITLE
at RecyclerView nested(嵌套) RecyclerView,an interesting problem....

### ISSUE THREAD

**Issue by ZengHongHua** [rubensousa/RecyclerViewSnap#51]
I have a problem,   at RecyclerView nested(嵌套) RecyclerView, It creates an interesting problem,  It's been rocking there.
can you help me,thank you very much.
this is the video connection:
https://res.cloudinary.com/liuyuesha/video/upload/v1540888109/test_snap_b2aa9s.mp4

Part of the code:
@Override
    public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, final int position) {

        if (holder instanceof RecommendSongsHolder) {
         
            FindBean.ModulesBean modulesBean = mFindDataList.get(position);
            List<FindRecommendSongInfo> program_list = modulesBean.getData().getTrack_list();

            LinearLayoutManager manager = new LinearLayoutManager(mContext, LinearLayoutManager.HORIZONTAL, false);
            ((RecommendSongsHolder) holder).recyclerView.setLayoutManager(manager);
            ((RecommendSongsHolder) holder).recyclerView.setHasFixedSize(true);
            ((RecommendSongsHolder) holder).recyclerView.setNestedScrollingEnabled(false);
            RecommendSongsChildAdapter songsChildAdapter = new RecommendSongsChildAdapter(mContext, mActivity, program_list, mDeviceDialog);
            ((RecommendSongsHolder) holder).recyclerView.setAdapter(songsChildAdapter);

            ((RecommendSongsHolder) holder).recyclerView.setOnFlingListener(null);
            SnapHelper snapHelper = new GravitySnapHelper(Gravity.START);
            snapHelper.attachToRecyclerView(((RecommendSongsHolder) holder).recyclerView);

        }

**Comment by rubensousa** [comment]
Do you have padding in your recyclerview? Can you share your layout's XML here?

**Comment by ZengHongHua** [comment]
>           Do you have padding in your recyclerview? Can you share your layout's XML here?

oh yes,I have set padding.
<RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingStart="20dp" >

**Comment by ZengHongHua** [comment]
code in my conpany, 
RecyclerView layout like this:
RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
       android:paddingStart="20dp"

**Comment by rubensousa** [comment]
Does it still happen if you remove the padding? I've been working on a fix for this tonight. Check the develop branch code and see if it works for you until I release the new version.

**Comment by ZengHongHua** [comment]
Sorry ,The project is for the company, Today is Sunday. I will try again tomorrow，thank you.

**Comment by ZengHongHua** [comment]
I remove the padding, it is ok.

**Comment by rubensousa** [comment]
Great :)
Will keep this open until 2.0 is released.

**Comment by rubensousa** [comment]
Fixed in 2.0
