### ISSUE TITLE
 GridLayoutManager.SpanSizeLookup  is not considered

### ISSUE THREAD

**Issue by ILAgent** [rubensousa/RecyclerViewSnap#52]
When we use GridLayoutManager not either element takes 1 cell. That's why logic 
`if (layoutManager instanceof GridLayoutManager) {
                offset += ((GridLayoutManager) layoutManager).getSpanCount() - 1;
            }`
is not correct. We need to consider results of `spanSizeLookup.getSpanSize`

**Comment by rubensousa** [comment]
Fixed in 2.0
