### ISSUE TITLE
Show the vertical recyclerview below the horizontal

### ISSUE THREAD

**Issue by fakebecak** [rubensousa/RecyclerViewSnap#54]
I've copied all the codes, but the vertical recyclerview  #doesnt appear.

**Comment by rubensousa** [comment]
I don't understand the problem here. The vertical recyclerview is shown when you click on "VERTICAL" on the toolbar

**Comment by pskr8209** [comment]
im facing error type 3.


Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.github.rubensousa.recyclerviewsnap/.MainActivity }
Error type 3
Error: Activity class {com.github.rubensousa.recyclerviewsnap/com.github.rubensousa.recyclerviewsnap.MainActivity} does not exist.

Error while Launching activity

How to solve this?

**Comment by rubensousa** [comment]
@pskr8209 you probably didn't add that Activity to your project. I'm going to close this due to inactivity.
