### ISSUE TITLE
Question: how to snap right away, and also while allowing first&last items to also be in center?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rubensousa/RecyclerViewSnap#55]
Suppose I want to snap to center, similar to this:

![aoxqg](https://user-images.githubusercontent.com/5357526/49025696-de38e000-f1a4-11e8-92e3-1638dcf7f0bb.gif)

Currently it seems that snapping only works after scrolling, and not right when we show the RecyclerView.

Also, it doesn't let me have the first and last items to be in the center.

**Comment by rubensousa** [comment]
Adding decoration or padding to the start and end of the recyclerview should work fine. Have you tried doing this?

Currently it seems that snapping only works after scrolling, -> You can do it programmatically by calling the public API of LinearSnapHelper.

**Comment by AndroidDeveloperLB** [comment]
I'm not sure if this is a good solution. What will happen if the content of the first/last item would change? And you have to decide how much space to add to it.
Isn't there another way to solve it? A way to let the RecyclerView to keep letting you scroll by what on the center?

**Comment by AndroidDeveloperLB** [comment]
I've made a question about it here:
https://stackoverflow.com/q/53483268/878126

**Comment by rubensousa** [comment]
RecyclerView lays out the items filling the whole available space (using the standard layout managers). You can't center the first or last items without adding some content on the edges. I don't think you can run away from a hacky solution for this. I'll try this out in the weekend.

**Comment by AndroidDeveloperLB** [comment]
But I thought that the LayoutManager is responsible about putting the Views and how to put each in its place...

**Comment by rubensousa** [comment]
They are, but if you're using a LinearLayoutManager the content is spread along the whole width of the RecyclerView.

**Comment by AndroidDeveloperLB** [comment]
Isn't there a way perhaps to override it, by extending  LinearLayoutManager ?

**Comment by rubensousa** [comment]
I'm sure there is, but I don't have time to try this out now. I'll check this in the weekend.

**Comment by rubensousa** [comment]
But I still think going for decoration is the easier way. You can have decoration that depends on the item width.

**Comment by AndroidDeveloperLB** [comment]
Easy solutions sometimes isn't the best thing to do.
Thank you for trying it out.

**Comment by rubensousa** [comment]
Managed to do it this night since I was curious :)
Video here: https://drive.google.com/open?id=1RPyiY9UndXcrbfBDWLB-UklxjPKMiR8-
This should do the trick:

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val adapter = Adapter()

        recyclerView.layoutManager = LinearLayoutManager(this, RecyclerView.HORIZONTAL, false)
        recyclerView.addItemDecoration(CenterDecoration(resources.getDimensionPixelSize(R.dimen.item_spacing)))
        recyclerView.adapter = adapter
        LinearSnapHelper().attachToRecyclerView(recyclerView)

        adapter.setItems(listOf("Panorama", "Portrait", "Camera", "Video", "More"))
    }
}

class CenterDecoration(@Px private val spacing: Int) : RecyclerView.ItemDecoration() {

    override fun getItemOffsets(outRect: Rect, view: View, parent: RecyclerView, state: RecyclerView.State) {
        super.getItemOffsets(outRect, view, parent, state)
        val adapterPosition = (view.layoutParams as RecyclerView.LayoutParams).viewAdapterPosition
        val lm = parent.layoutManager as LinearLayoutManager
        if (adapterPosition == 0) {
            outRect.left = parent.width / 2 - view.width / 2
            outRect.right = spacing / 2
        } else if (adapterPosition == lm.itemCount - 1) {
            outRect.right = parent.width / 2 - view.width / 2
            outRect.left = spacing / 2
        } else {
            outRect.left = spacing / 2
            outRect.right = spacing / 2
        }
    }

}
```

**Comment by AndroidDeveloperLB** [comment]
Seems promising.
Can you please put full solution? Here's a link:
https://stackoverflow.com/q/53483268/878126

**Comment by rubensousa** [comment]
It has some problems though: doesn't work when there's less than 3 items. This probably requires a custom snap helper :)

**Comment by AndroidDeveloperLB** [comment]
Oh, but I want to be able to set various number of items... :(

**Comment by rubensousa** [comment]
Managed to fix this. Will update my answer on stackoverflow soon.

**Comment by AndroidDeveloperLB** [comment]
Thank you
