### ISSUE TITLE
how set adapter for that

### ISSUE THREAD

**Issue by RahimpourDeveloper** [rubensousa/RecyclerViewSnap#61]
hello
I can't set adapter for gravitySnapHelper!
and I can't find java code for that
can you help me, please?

**Comment by rubensousa** [comment]
You can't set an adapter for a SnapHelper. The adapter is set on the RecyclerView.
```java
GravitySnapHelper snapHelper = new GravitySnapHelper(Gravity.START);
snapHelper.attachToRecyclerView(recyclerView);
```
