### ISSUE TITLE
the first item cannot snap to center

### ISSUE THREAD

**Issue by jizhe7550** [rubensousa/RecyclerViewSnap#62]
When I try to set the gravity as Center and set the startPadding as the mid of the phone screen in horizontal, I found I cannot snap the first and the last view in some phone, such as Pixel, and it seems the second item is nearest than the first item to centre, but I don't know what I can change if I want to snap the first view in this situation, plz help me, thank you. 

the decoration code
<dimen name="circle_width">80dp</dimen>

   recyclerView.addItemDecoration(
            LinearEdgeDecoration(
                startPadding = screenWidth() / 2
                 - resources.getDimension(R.dimen.circle_width).toInt() / 2,
                orientation = RecyclerView.HORIZONTAL
            )
        )

**Comment by fupduck** [comment]
@jizhe7550 
For me it helped adding padding to the RecyclerView
```
        android:clipToPadding="false"
        android:paddingLeft="100dp"
        android:paddingRight="100dp"
```

**Comment by rubensousa** [comment]
You need to have enough decoration or padding set for that to work. The sample app has a "Center with decoration" example
