### ISSUE TITLE
Library artifacts are published to jcenter only, which will close in 3 months

### ISSUE THREAD

**Issue by entibaldi** [rubensousa/RecyclerViewSnap#71]
Hello! Your library is published only to jcenter. Please consider publishing it also to mavenCentral, as jcenter is [shutting down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

[Here](https://central.sonatype.org/pages/producers.html) is some info on how to publish artifacts to mavenCentral.

**Comment by rubensousa** [comment]
Latest release is now in mavenCentral: https://s01.oss.sonatype.org/content/groups/public/com/github/rubensousa/gravitysnaphelper/2.2.1/
