### ISSUE TITLE
Could not download package

### ISSUE THREAD

**Issue by michblazek** [rubensousa/RecyclerViewSnap#73]
Hello, i'd like to try your implementation, but I am not able to download the package;

`
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.rubensousa:gravitysnaphelper:2.2.1
Could not get resource 'https://jcenter.bintray.com/com/github/rubensousa/gravitysnaphelper/2.2.1/gravitysnaphelper-2.2.1.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/github/rubensousa/gravitysnaphelper/2.2.1/gravitysnaphelper-2.2.1.aar'.
Read timed out
`

**Comment by rubensousa** [comment]
Hi there. That should not happen, but I'm already taking care of uploading this to mavenCentral. Will you let you know once it's available

**Comment by tyates** [comment]
The error itself is because Bintray had an outage at that time:
https://status.bintray.com/
